/*=============================================================================================================
# Author: Kabeli Charles 202000679
# Email: kabeli.charles@gmail.com
# Phone: +26656243089
# Date:  October 12, 2022
# Functional description: This is the program that determines and prints the first 10 reversible prime squares
#=============================================================================================================*/

#include <stdio.h>
#include <stdbool.h>

//THE FOLLOWING FUNCTION CHECKS IF A NUMBER IS A PRIME 
bool Is_Prime(int n){			// it is a boolean function that returns True if the number is a prime, or returns false if it is not.
	int factors=0;				// initialise the factors of a number to 0
	for(int i=1; i<=n; i++){	// perform the following instructions for as long as a devisor is less than or equal to the number being devided
		if(n%i==0)				// if the remaider is 0 increment the variable factors 
			factors++;
	}
	if (factors==2)				// a prime number has two factors, therefore if the number being devided has two factors, return True
		return true;
	else 
		return false;			// if it has more or less than two factors, it is not the prime number, thefore return false
}


// THE FOLLOWING IS THE FUNCTION THAT REVERSES A NUMBER
int Reverse(int n)
{
	int reverse=0;        //Initialise the reverse of a number to 0
	while(n!=0)			// perform the following instructions until the number =0
	{
		reverse=reverse*10+n%10;	//we reverse a number by isolating its last digit from the number(n%10)
								    //then append the removed digit to the last part of the remainder. (remaider=(remainder*10) + the last digit)
		n/=10;                		//removes the last digit from the number... this is done until the whole number is gone
	}
	return reverse;					//return the value of the reverse of a number
}

//THE FOLLOWING FUNCTION CHECKS IF A NUMBER IS A PALINDROME
// it is a boolean function which returns True or False
// it takes the two parameters being a number and its reverse (generated by the Reverse function above) to check if they are equal
bool Is_Palindrome(int n, int m)  
{
	if(n==m)
		return true;		//if the number is equal to its reverse, return True. Thus, the number is a palindrome
	else 
		return false;		// else return False. Thus, the number is not a palindrome
}

//THE FOLLOWING FUNCTON CHECKS IF A NUMBER IS A SQUARE OF A PRIME
bool Is_Square(int m)
{
	bool TrueOrFalse=false;          //initialise the boolean value to False
	for(int i=1; i<=m; i++){		// i is the devisor and m is the number to be checked if it is prime
		if(m/i==i && m%i==0){		//for a number to be a square, two conditions have to be met. The result when deviding a number has to be equal to the devisor. Thus n/i=i,
									// and the remainder has to be equal to 0
			if(Is_Prime(i)){			// if a number is a square, call the IS_Prime function to see if the devisor (its square root) is a prime number.
				TrueOrFalse=true;	// if it is the prime number, the boolean value becomes True
			}
			else {
				TrueOrFalse=false;	//otherwise it is False.
			}
		}
}
	return TrueOrFalse;				//return the boolean value
}

int main(){
	printf("\n THE FIRST 10 REVERSIBLE PRIME SQUARES ARE: \n");
	int ReversiblePrimeSquares[10];   // an array that is going to store the first 10 reversible prime squares
	int number=1; 						// initialise the first number to be checked to 1
	int square;						// a variable to store the square of a number
	for(int i=0; i<=9; i++){		
		while(i<10){				//repeat this loop until the array is full. thus, we have found all the 10 elements (first 10 reversible prime squares)
			if(Is_Prime(number))	//calls Is_Prime function to check if the number is a prime
			{
				square=number*number; //find the square of a number
				if(Is_Palindrome(square, Reverse(square))){ // calls a Is_Palindrome function giving it the two parameters being 
															//the square and its reverse (generated by the Reverse function), to check if they are equal
					number++; 		// if they are equal increment a number to perform the above operations on the next number
				}
				else{				// thus the number is not a palindrome
					if(Is_Square(Reverse(square))) // checks if the reverse of a square is also a prime
					  {
					  	ReversiblePrimeSquares[i]=square;  // if it is the prime, store the square in the ith position of the array.
					  	number++;							//increment the number
					  	break;
					  }
					  else{					// if the reverse of a square is not a prime increment the initial number without doing any operations
					  	number++;
					  }
					
				}				
				 
			}
			else number++;    //if the square of the initial number is not a number
		
		}
	}
	
	// Print the reversible prime squares stored in an array.
	for(int i=0; i<10; i++)
	{
		printf(" %d: %d\n",i+1,  ReversiblePrimeSquares[i]);
	}


	
	return 0;
}